meta:
  version: "2.4.0"
  updated: "2025-12-11"
  trusted: 42
  flagged: 14
  sources:
    - newsguardtech.com
    - spamhaus.org

trusted_domains:
  - nature.com
  - reuters.com
  - nytimes.com
  - bbc.com
  - theguardian.com
  - jstor.org
  - pubmed.ncbi.nlm.nih.gov
  - nih.gov
  - arxiv.org
  - stackoverflow.com
  - github.com
  - "*.gov"

flagged_domains:
  - breitbart.com
  - infowars.com
  - zerohedge.com
  - rt.com
  - globaltimes.cn
  - newsmax.com
  - beforeitsnews.com
